
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "fullName" : "Isaac Emmanuel",
    "email" : "isaacemmanuel1913@gmail.com",
    "password" : "mysecurepassword",
    "role" : "admin"
}

###

POST http://localhost:5000/auth/verify
Content-Type: application/json

{
   "email" : "isaacemmanuel1913@gmail.com",
    "otp" : 9280,
    "purpose" : "verify-email"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
   "email" : "isaacemmanuel1913@gmail.com",
    "password" : "mysecurepassword"
}

###

POST   http://localhost:5000/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE4NTcyMDNjOTExYjJjMzg0YmE2YzQiLCJlbWFpbCI6ImlzYWFjZW1tYW51ZWwxOTEzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NTg3MjkxN30.mQsgypO9B8gGHZ2I9hfs7f89GlEL0e6jvp1W60dfNsU

{
    "item": [
       {
         "productName": "Gucci mini GG bag",
        "quantity": 1
       },
       {
         "productName": "Air nike",
        "quantity": 2
       }
    ]
}


###

DELETE    http://localhost:5000/brands/68a113489a91b446ab3e9f82
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODllOGRhNTU4YzQ4YWU0MTJhYWIwYmUiLCJlbWFpbCI6ImlzYWFjZW1tYW51ZWwxOTEzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NTIyMTg1N30.HopwRsq_oYbUNMc4-v1vFbZdg6GN6bovcHAw4W1DC5w


###

GET http://localhost:5000/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE4NTcyMDNjOTExYjJjMzg0YmE2YzQiLCJlbWFpbCI6ImlzYWFjZW1tYW51ZWwxOTEzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NTg3MzQzOH0.w6M9zKjgQwFTSmI6z-DgMu8ggC34TxMYxGkcufAC-k8

###

PATCH http://localhost:5000/order/68ac97bd558a951171c5b8aa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE4NTcyMDNjOTExYjJjMzg0YmE2YzQiLCJlbWFpbCI6ImlzYWFjZW1tYW51ZWwxOTEzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NjU4NTE1N30.gdQ9mBZ2BFL-E9F2Fbk39rmEtBf6Td3B0SpzNMrFGEk

{
  "shippingStatus": "shipped"
}

###

GET http://localhost:5000/order/68a87b1b175af6694f7d374e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE4NTcyMDNjOTExYjJjMzg0YmE2YzQiLCJlbWFpbCI6ImlzYWFjZW1tYW51ZWwxOTEzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NTg3MzQzOH0.w6M9zKjgQwFTSmI6z-DgMu8ggC34TxMYxGkcufAC-k8 


###

GET http://localhost:5000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE4NmVlYjI1MGNiMTZiZGUxYjY1M2UiLCJlbWFpbCI6ImRvcGU5ODU3N0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NTY1ODQ3ODJ9.iAvfgiV7oiy68r4ln9PoD9rz0wO50gXqs8Kscdj91YE


### 

GET http://localhost:5000/order-history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE4NTcyMDNjOTExYjJjMzg0YmE2YzQiLCJlbWFpbCI6ImlzYWFjZW1tYW51ZWwxOTEzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NjgxNDExNX0.2gc3XLkMhH4jjIfulo5Bi4XWG4er8T9BJii36-xXln8
